<Project Sdk="Godot.NET.Sdk/4.6.1">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>BestagonDefence</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Editor\**" />
    <Compile Remove="Gameplay\DiscordController.cs" />
    <Compile Remove="Gameplay\Controls\**" />
    <Compile Remove="MaterialLibrary\**" />
    <Compile Remove="Modules\_NeedRebalance\**" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Remove="Editor\**" />
    <EmbeddedResource Remove="Gameplay\Controls\**" />
    <EmbeddedResource Remove="MaterialLibrary\**" />
    <EmbeddedResource Remove="Modules\_NeedRebalance\**" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Levels\Music\" />
  </ItemGroup>
</Project>