name: Bestagon-Defence build

on:
  push:
#  pull_request: 
#    types:
#      - opened
  workflow_dispatch:

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ${{ matrix.jobOS }}
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        include:
          # Temporarily disabled as it wasn't working
          - targetPlatform: StandaloneOSX # Build a macOS standalone (Intel 64-bit).
            jobOS: ubuntu-latest
#          - targetPlatform: StandaloneWindows # Build a Windows standalone.
#            jobOS: ubuntu-latest
#          - targetPlatform: StandaloneWindows64 # Build a Windows 64-bit standalone.
#            jobOS: ubuntu-latest
#          - targetPlatform: StandaloneLinux64 # Build a Linux 64-bit standalone.
#            jobOS: ubuntu-latest
#          - targetPlatform: iOS # Build an iOS player.
#            jobOS: ubuntu-latest
#          - targetPlatform: Android # Build an Android .apk standalone app.
#            jobOS: ubuntu-latest
#          - targetPlatform: WebGL # WebGL.
#            jobOS: ubuntu-latest
        
    outputs:
      StandaloneOSX: ${{ steps.outputResult.outputs.StandaloneOSX }}
#      StandaloneWindows: ${{ steps.outputResult.outputs.StandaloneWindows }}
#      StandaloneWindows64: ${{ steps.outputResult.outputs.StandaloneWindows64 }}
#      StandaloneLinux64: ${{ steps.outputResult.outputs.StandaloneLinux64 }}
      #iOS: ${{ steps.outputResult.outputs.iOS }}
#      Android: ${{ steps.outputResult.outputs.Android }}
      #WebGL: ${{ steps.outputResult.outputs.WebGL }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
            
#      - uses: jlumbroso/free-disk-space@main
#        with:
#          # this might remove tools that are actually needed,
#          # if set to "true" but frees about 6 GB
#          tool-cache: false
#          
#          # all of these default to true, but feel free to set to
#          # "false" if necessary for your workflow
#          android: true
#          dotnet: true
#          haskell: false
#          large-packages: true
#          docker-images: true
#          swap-storage: true
          
#      - name: Setup Android SDK
#        uses: android-actions/setup-android@v3
#        if: ${{ matrix.targetPlatform != 'Android' }}
      
      - id: ls
        run: echo "ls './Tower Defense''

      - name: export game
        id: export
        # Use latest version (see releases for all versions)
        uses: firebelley/godot-export@v6.0.0
        with:
          # Defining all the required inputs
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v4.4.1-stable_mono_linux_x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v4.4.1-stable_mono_export_templates.tpz
          relative_project_path: "./Tower Defense/"
          verbose: true
          archive_output: true
#          presets_to_export: ${{ matrix.targetPlatform }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.targetPlatform }}
          path: |
            ${{ steps.export.outputs.archive_directory }}/*
            !*DoNotShip/
      
      - id: outputResult
        run: echo "${{ matrix.targetPlatform }}Result=${{ job.status }}" >> $GITHUB_ENV
  
  sendSuccessNotification:
    runs-on: ubuntu-latest
    needs:
      - buildForAllSupportedPlatforms
    if: ${{ success() }}
    steps:
      - uses: tsickert/discord-webhook@v6.0.0
        with:
          webhook-url: ${{ secrets.NIGHTLY_WEBHOOK_URL }}
          content: "Build Success"
          embed-title: "New Development Build Available!"
          embed-description: "[You can get the new builds here](https://github.com/Greenfoot5/Bestagon-Defence/actions/runs/${{ github.run_id }})
          \n${{ env.StandaloneWindowsResult }}\n*You may need to log in & scroll down to the bottom*"
          embed-color: 1546855
      
  sendFailureNotification:
    runs-on: ubuntu-latest
    needs: 
      - buildForAllSupportedPlatforms
    if: ${{ failure() }}
    steps:
      - uses: tsickert/discord-webhook@v6.0.0
        with:
          webhook-url: ${{ secrets.NIGHTLY_WEBHOOK_URL }}
          content: "Build Failure"
          embed-title: "New Development Build Failed!"
          embed-description: "[You can find the results here](https://github.com/Greenfoot5/Bestagon-Defence/actions/runs/${{ github.run_id }})\n${{ env.StandaloneWindowsResult }}"
          embed-color: 10949957
      
