name: Bestagon-Defence build

on:
  push:
#  pull_request: 
#    types:
#      - opened
  workflow_dispatch:
    
env:
  GODOT_VERSION: 4.4.1
  EXPORT_NAME: BestagonDefense-Nightly
  PROJECT_PATH: "Tower\ Defense"

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ${{ matrix.jobOS }}
    container: barichello/godot-ci:mono-4.4.1
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        include:
          # Temporarily disabled as it wasn't working
          - targetPlatform: macOS # Build a macOS standalone (Intel 64-bit).
            jobOS: ubuntu-latest
#          - targetPlatform: StandaloneWindows # Build a Windows standalone.
#            jobOS: ubuntu-latest
#          - targetPlatform: StandaloneWindows64 # Build a Windows 64-bit standalone.
#            jobOS: ubuntu-latest
#          - targetPlatform: StandaloneLinux64 # Build a Linux 64-bit standalone.
#            jobOS: ubuntu-latest
#          - targetPlatform: iOS # Build an iOS player.
#            jobOS: ubuntu-latest
#          - targetPlatform: Android # Build an Android .apk standalone app.
#            jobOS: ubuntu-latest
#          - targetPlatform: WebGL # WebGL.
#            jobOS: ubuntu-latest
        
    outputs:
      StandaloneOSX: ${{ steps.outputResult.outputs.StandaloneOSX }}
#      StandaloneWindows: ${{ steps.outputResult.outputs.StandaloneWindows }}
#      StandaloneWindows64: ${{ steps.outputResult.outputs.StandaloneWindows64 }}
#      StandaloneLinux64: ${{ steps.outputResult.outputs.StandaloneLinux64 }}
      #iOS: ${{ steps.outputResult.outputs.iOS }}
#      Android: ${{ steps.outputResult.outputs.Android }}
      #WebGL: ${{ steps.outputResult.outputs.WebGL }}

    steps:
      - uses: actions/checkout@v4
        with:
#          fetch-depth: 0
          lfs: true
            
#      - uses: jlumbroso/free-disk-space@main
#        with:
#          # this might remove tools that are actually needed,
#          # if set to "true" but frees about 6 GB
#          tool-cache: false
#          
#          # all of these default to true, but feel free to set to
#          # "false" if necessary for your workflow
#          android: true
#          dotnet: true
#          haskell: false
#          large-packages: true
#          docker-images: true
#          swap-storage: true

#      - name: Setup
#        run: |
#          mkdir -v -p ~/.local/share/godot/export_templates/
#          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - run: ls
      
      - name: export
        run: |
          mkdir -v -p build/${{matrix.targetPlatform}}
          EXPORT_DIR="$(readlink -f build)"
          ls -a
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "${{ matrix.targetPlatform }}" "$EXPORT_DIR/${{matrix.targetPlatform}}/$EXPORT_NAME.zip"

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.targetPlatform }}
          path: build/${{matrix.targetPlatform}}
      
      - id: outputResult
        run: echo "${{ matrix.targetPlatform }}Result=${{ job.status }}" >> $GITHUB_ENV
  
  sendSuccessNotification:
    runs-on: ubuntu-latest
    needs:
      - buildForAllSupportedPlatforms
    if: ${{ success() }}
    steps:
      - uses: tsickert/discord-webhook@v6.0.0
        with:
          webhook-url: ${{ secrets.NIGHTLY_WEBHOOK_URL }}
          content: "Build Success"
          embed-title: "New Development Build Available!"
          embed-description: "[You can get the new builds here](https://github.com/Greenfoot5/Bestagon-Defence/actions/runs/${{ github.run_id }})
          \n${{ env.StandaloneWindowsResult }}\n*You may need to log in & scroll down to the bottom*"
          embed-color: 1546855
      
  sendFailureNotification:
    runs-on: ubuntu-latest
    needs: 
      - buildForAllSupportedPlatforms
    if: ${{ failure() }}
    steps:
      - uses: tsickert/discord-webhook@v6.0.0
        with:
          webhook-url: ${{ secrets.NIGHTLY_WEBHOOK_URL }}
          content: "Build Failure"
          embed-title: "New Development Build Failed!"
          embed-description: "[You can find the results here](https://github.com/Greenfoot5/Bestagon-Defence/actions/runs/${{ github.run_id }})\n${{ env.StandaloneWindowsResult }}"
          embed-color: 10949957
      
