name: Bestagon-Defence build

on:
  push:
  pull_request: 
    types:
      - opened
  workflow_dispatch:

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.exportName }}
    runs-on: ${{ matrix.jobOS }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - exportName: macOS
            jobOS: ubuntu-latest
            # Must match platform in here https://github.com/firebelley/godot-export/blob/master/src/types/GodotExport.ts
          - exportName: Windows
            jobOS: ubuntu-latest
#          - exportName: StandaloneLinux64 # Build a Linux 64-bit standalone.
#            jobOS: ubuntu-latest
#            platform: 
#          - exportName: Android # Build an Android .apk standalone app.
#            jobOS: ubuntu-latest
        
    outputs:
      StandaloneOSX: ${{ steps.outputResult.outputs.StandaloneOSX }}
      StandaloneWindows: ${{ steps.outputResult.outputs.StandaloneWindows }}
#      StandaloneWindows64: ${{ steps.outputResult.outputs.StandaloneWindows64 }}
#      StandaloneLinux64: ${{ steps.outputResult.outputs.StandaloneLinux64 }}
      #iOS: ${{ steps.outputResult.outputs.iOS }}
#      Android: ${{ steps.outputResult.outputs.Android }}
      #WebGL: ${{ steps.outputResult.outputs.WebGL }}

    steps:
      - uses: actions/checkout@v6

      - name: export game
        uses: firebelley/godot-export@v7.0.0
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.6.1-stable/Godot_v4.4.1-stable_mono_linux_x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.6.1-stable/Godot_v4.4.1-stable_mono_export_templates.tpz
          relative_project_path: "./TowerDefence"
          relative_export_path: "./build/${{matrix.exportName}}"
          archive_output: true
          presets_to_export: ${{ matrix.exportName }}

      - uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.exportName }}
          path: build/${{matrix.exportName}}
      
      - id: outputResult
        run: echo "${{ matrix.exportName }}Result=${{ job.status }}" >> $GITHUB_ENV
  
  sendSuccessNotification:
    runs-on: ubuntu-latest
    needs:
      - buildForAllSupportedPlatforms
    if: ${{ success() && github.event_name != 'pull_request' }} 
    steps:
      - uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.NIGHTLY_WEBHOOK_URL }}
          content: "Build Success"
          embed-title: "New Development Build Available!"
          embed-description: "[You can get the new builds here](https://github.com/Greenfoot5/Bestagon-Defence/actions/runs/${{ github.run_id }})
          \n${{ env.StandaloneWindowsResult }}\n*You may need to log in & scroll down to the bottom*"
          embed-color: 1546855
      
  sendFailureNotification:
    runs-on: ubuntu-latest
    needs: 
      - buildForAllSupportedPlatforms
    if: ${{ failure() && github.event_name != 'pull_request' }}
    steps:
      - uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.NIGHTLY_WEBHOOK_URL }}
          content: "Build Failure"
          embed-title: "New Development Build Failed!"
          embed-description: "[You can find the results here](https://github.com/Greenfoot5/Bestagon-Defence/actions/runs/${{ github.run_id }})\n${{ env.StandaloneWindowsResult }}"
          embed-color: 10949957
      
